name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build --pull --rm -f "demo-app/Dockerfile" -t dockerangular:latest -t dockerangular:<your_tag> "demo-app"

    - name: Log in to Docker Hub
      run: docker login -u saralaaa -p ${{ secrets.dckr_pat_gWx_UJ5CQDaYYk-rTScZUAMkxL0 }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push saralaaa/dockerangular:latest
        docker push saralaaa/dockerangular:<your_tag>
