name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t dockerangular .
        docker tag dockerangular:latest ${{ secrets.saralaaa }}/dockerangular:latest

    - name: Log in to Docker Hub
      run: docker login -u saralaaa -p ${{ secrets.dckr_pat_gWx_UJ5CQDaYYk-rTScZUAMkxL0 }}

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.saralaaa }}/dockerangular:latest
